name: dartchess
description: Native chess rules library.
version: 0.1.0
homepage: https://github.com/alexrintt/lichess.dart

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  fast_immutable_collections: ^9.0.0
  meta: ^1.8.0

dev_dependencies:
  benchmark: ^0.3.0
  lint: ^2.0.1
  test: ^1.16.0
